# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-audit-test',
                'doc_host': 'https://devdatalab.github.io',
                'git_url': 'https://github.com/devdatalab/data-audit-test',
                'lib_path': 'data_audit_test'},
  'syms': {'data_audit_test.core': {'data_audit_test.core.foo': ('core.html#foo', 'data_audit_test/core.py')}}}
